### ISSUE TITLE
[Crash] when drawing armor: net.minecraft.item.ItemStack cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by commandhat** [Wynncraft/Issues#2383]
Something's up with my Archer. When I try to select him, I get to see my loaded location for a minute, then Minecraft gives me the "loading screen w/ dirt background", then it crashes. I doubt this has anything to do with drawing armor though that's where it crashes.

Journeymap is involved and may be the reason for this, though I'm not totally sure. Will make another post and (if I can) close this issue if this is the case.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/10/15 8:40 PM
Description: Exception in world tick

java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to java.lang.String
	at net.minecraft.entity.DataWatcher.func_75681_e(SourceFile:108)
	at net.minecraft.entity.Entity.func_145818_k_(Entity.java:2253)
	at net.minecraft.entity.Entity.func_70005_c_(Entity.java:2039)
	at journeymap.client.forge.helper.impl.ForgeHelper_1_8.getItemName(ForgeHelper_1_8.java:214)
	at journeymap.client.network.WorldInfoHandler.on(WorldInfoHandler.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_WorldInfoHandler_on_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1134)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:85)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2113)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1029)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by commandhat** [comment]
Yup, removing journeymap fixes it. Though amusingly if I keep Journeymap open and login-crash like this several times in a row, I move one block higher into the air each time.

**Comment by commandhat** [comment]
Revisiting the issue for those of you that have the same problem: Just load the world without Journeymap, and the issue will go-away when you put Journeymap back.
