### ISSUE TITLE
Minecraft is keeps crashing in this one quest castle

### ISSUE THREAD

**Issue by IceC00kie** [Wynncraft/Issues#2898]
My mc keeps crashing when I enter a castle. I don't know wich quest it is but I think it is in the dark forest and the family murdered themselves. Here my crash report: 
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 22.12.15 21:49
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.getExtendedState(Block.java:2052)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:151)
	at net.minecraft.client.renderer.entity.RenderFallingBlock.func_76986_a(SourceFile:63)
	at net.minecraft.client.renderer.entity.RenderFallingBlock.func_76986_a(SourceFile:20)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:374)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:331)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:298)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:652)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.BlockFence.func_176221_a(SourceFile:159)
	at net.minecraft.block.Block.getExtendedState(Block.java:2052)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:151)
	at net.minecraft.client.renderer.entity.RenderFallingBlock.func_76986_a(SourceFile:63)
	at net.minecraft.client.renderer.entity.RenderFallingBlock.func_76986_a(SourceFile:20)

-- Entity being rendered --
Details:
	Entity Type: FallingSand (net.minecraft.entity.item.EntityFallingBlock)
	Entity ID: 246757
	Entity Name: Falling Block
	Entity's Exact location: -1239,50, 15,00, -7758,50
	Entity's Block location: -1240,00,15,00,-7759,00 - World: (-1240,15,-7759), Chunk: (at 8,0,1 in -78,-485; contains blocks -1248,0,-7760 to -1233,255,-7745), Region: (-3,-16; contains chunks -96,-512 to -65,-481, blocks -1536,0,-8192 to -1025,255,-7681)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Immitating block ID: 85
	Immitating block data: 0

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderFallingBlock@50c8b73
	Location: 1,12,1,12,-36,21 - World: (1,1,-37), Chunk: (at 1,0,11 in 0,-3; contains blocks 0,0,-48 to 15,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 0.0
	Delta: 0.7712357
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:374)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:331)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:298)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:652)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['IceC00kie'/6147, l='MpServer', x=-1240,63, y=13,86, z=-7722,29]]
	Chunk stats: MultiplayerChunkCache: 366, 366
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -1583,00,53,00,-1636,00 - World: (-1583,53,-1636), Chunk: (at 1,3,12 in -99,-103; contains blocks -1584,0,-1648 to -1569,255,-1633), Region: (-4,-4; contains chunks -128,-128 to -97,-97, blocks -2048,0,-2048 to -1537,255,-1537)
	Level time: 1255503918 game time, 5595039 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityVillager['Villager'/246739, l='MpServer', x=-1238,50, y=14,00, z=-7708,50], EntityOtherPlayerMP['NordicVenturer'/137311, l='MpServer', x=-978,00, y=61,94, z=-1693,00], EntityArmorStand['§7Quest NPC'/246738, l='MpServer', x=-1260,50, y=15,50, z=-7729,50], EntityArmorStand['§2Check'/246737, l='MpServer', x=-1260,50, y=15,78, z=-7729,50], EntityPainting['Painting'/246680, l='MpServer', x=-1212,50, y=16,00, z=-7725,03], EntityItem['item.item.paper'/246736, l='MpServer', x=-1260,50, y=15,00, z=-7729,50], EntityItemFrame['entity.ItemFrame.name'/246679, l='MpServer', x=-1222,50, y=9,50, z=-7703,97], EntityPainting['Painting'/246681, l='MpServer', x=-1212,50, y=14,50, z=-7704,03], EntityArmorStand['§2Mr. Caritat'/246743, l='MpServer', x=-1220,50, y=16,31, z=-7722,50], EntityPainting['Painting'/246682, l='MpServer', x=-1212,50, y=16,50, z=-7701,97], EntityVillager['Villager'/246742, l='MpServer', x=-1220,50, y=14,00, z=-7722,50], EntityArmorStand['§7Quest NPC'/246741, l='MpServer', x=-1238,50, y=16,06, z=-7708,50], EntityArmorStand['§2Maid'/246740, l='MpServer', x=-1238,50, y=16,31, z=-7708,50], EntityArmorStand['§7Quest NPC'/246747, l='MpServer', x=-1221,50, y=15,50, z=-7722,50], EntityPainting['Painting'/246682, l='MpServer', x=-1212,50, y=16,50, z=-7701,97], EntityArmorStand['§2Mr. Caritat's Journal'/246746, l='MpServer', x=-1221,50, y=15,78, z=-7722,50], EntityPainting['Painting'/246681, l='MpServer', x=-1212,50, y=14,50, z=-7704,03], EntityItem['item.item.writingBook'/246745, l='MpServer', x=-1221,50, y=15,00, z=-7722,50], EntityPainting['Painting'/246680, l='MpServer', x=-1212,50, y=16,00, z=-7725,03], EntityArmorStand['§7Quest NPC'/246744, l='MpServer', x=-1220,50, y=16,06, z=-7722,50], EntityVillager['Villager'/246751, l='MpServer', x=-1232,50, y=14,00, z=-7741,50], EntityItem['item.tile.tripWireSource'/247455, l='MpServer', x=-1228,50, y=8,00, z=-7702,50], EntityArmorStand['§7Quest NPC'/246750, l='MpServer', x=-1239,50, y=16,13, z=-7738,50], EntityArmorStand['§2Servant'/246749, l='MpServer', x=-1239,50, y=16,38, z=-7738,50], EntityVillager['Villager'/246748, l='MpServer', x=-1239,50, y=14,06, z=-7738,50], EntityArmorStand['§2Timmy Caritat'/246755, l='MpServer', x=-1237,50, y=16,31, z=-7744,50], EntityVillager['Villager'/246754, l='MpServer', x=-1237,50, y=14,00, z=-7744,50], EntityArmorStand['§7Quest NPC'/246753, l='MpServer', x=-1232,50, y=16,06, z=-7741,50], EntityArmorStand['§2Maid'/246752, l='MpServer', x=-1232,50, y=16,31, z=-7741,50], EntityArmorStand['§aLibrary Key§6 [Lv. 0]'/247456, l='MpServer', x=-1228,50, y=8,50, z=-7702,50], EntityArmorStand['§7Quest NPC'/246759, l='MpServer', x=-1239,50, y=16,25, z=-7758,50], EntityArmorStand['§2Library Door'/246758, l='MpServer', x=-1239,50, y=16,50, z=-7758,50], EntityFallingBlock['Falling Block'/246757, l='MpServer', x=-1239,50, y=15,00, z=-7758,50], EntityArmorStand['§7Quest NPC'/246756, l='MpServer', x=-1237,50, y=16,06, z=-7744,50], EntityPlayerSP['IceC00kie'/6147, l='MpServer', x=-1240,63, y=13,86, z=-7722,29]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"9cf57ca":1068) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 279413936 bytes (266 MB) / 679219200 bytes (647 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.18 Powered by Forge 11.15.0.1637 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.8-11.15.0.1637-1.8.8.jar) 
	UCHIJA	Forge{11.15.0.1637} [Minecraft Forge] (forge-1.8.8-11.15.0.1637-1.8.8.jar) 
	UCHIJA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.00' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
	Launched Version: 1.8.8-forge1.8.8-11.15.0.1637-1.8.8
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 359.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

**Comment by Trixter313** [comment]
I see that you're using Forge. Does it crash even with vanilla Minecraft?
