### ISSUE TITLE
Item Lost Log PROOF StabSand

### ISSUE THREAD

**Issue by Lambirisk** [Wynncraft/Issues#3248]
I lost my item while identifying it here is my log go into the server personal log and plz help me with my item it was my first assassin legendary item

[14:12:14] [Client thread/INFO]: Reloading ResourceManager: Default, legacy
[14:12:14] [Client thread/INFO]: SoundSystem shutting down...
[14:12:15] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[14:12:15] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:12:15] [Thread-22/INFO]: Initializing LWJGL OpenAL
[14:12:15] [Thread-22/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:12:15] [Thread-22/INFO]: OpenAL initialized.
[14:12:15] [Sound Library Loader/INFO]: Sound engine started
[14:12:17] [Client thread/INFO]: Created: 2048x1024 textures-atlas
[14:12:17] [Client thread/INFO]: [CHAT] Thank you for using the WynnPack. Enjoy the game!
[14:12:27] [Client thread/INFO]: [CHAT] jumppuff13 has logged into server WC46 as an Archer
[14:12:35] [Client thread/INFO]: [CHAT] 69Teemo69 has logged into server WC45 as a Ninja
[14:13:37] [Client thread/INFO]: [CHAT] 69Teemo69 has logged into server WC46 as a Ninja
[14:15:23] [Client thread/INFO]: [CHAT] [1/4] Vade: Oh, hey kid. Wanna make some money?
[14:15:24] [Client thread/INFO]: [CHAT] [2/4] Vade: I need you to translate this ancient text.
[14:15:26] [Client thread/INFO]: [CHAT] [3/4] Vade: Just run it down to the lab assistant, Tesha.
[14:15:28] [Client thread/INFO]: [CHAT] [4/4] Vade: I'd take it myself, but I'm far too important for grunt work! The lab is up there in the tent, and don't you dare damage the translation!
[14:15:34] [Client thread/INFO]: [CHAT] [Quest Started: WynnExcavation Site A]
[14:15:39] [Client thread/INFO]: [CHAT] [Questline Started: WynnExcavation]
[14:16:10] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:16:26] [Client thread/INFO]: [CHAT] [1/8] Tesha: Hello, welcome to WynnExcavation Labs!
[14:16:28] [Client thread/INFO]: [CHAT] [2/8] Tesha: Oh Vade sent you?
[14:16:28] [Client thread/INFO]: [CHAT] [3/8] Tesha: Oh yes, the tablet I was waiting for!
[14:16:28] [Client thread/INFO]: [CHAT] [4/8] Tesha: ...
[14:16:28] [Client thread/INFO]: [CHAT] [5/8] Tesha: Oh my! This is quite interesting..
[14:16:28] [Client thread/INFO]: [CHAT] [6/8] Tesha: Here let me finish this up...
[14:16:29] [Client thread/INFO]: [CHAT] [7/8] Tesha: ..and there you are!
[14:16:30] [Client thread/INFO]: [CHAT] [8/8] Tesha: One tablet complete! Return it to Vade. Oh and don't read it!
[14:16:35] [Client thread/INFO]: [CHAT] [Quest Book Updated]
[14:16:48] [Client thread/INFO]: [CHAT] [1/6] Vade: Who are you?
[14:16:49] [Client thread/INFO]: [CHAT] [2/6] Vade: Oh right, you're that kid I sent out!
[14:16:50] [Client thread/INFO]: [CHAT] [3/6] Vade: Well do you have the translated text or not?
[14:16:52] [Client thread/INFO]: [CHAT] [4/6] Vade: You do! Brilliant! Let's take a look at that...
[14:16:52] [Client thread/INFO]: [CHAT] [5/6] Vade: "Throw tribute an item to the wood that stands out, the right angle will open the way"
[14:16:53] [Client thread/INFO]: [CHAT] [6/6] Vade: I wonder if it is talking about inside the temple… Oh, uh, I forgot you were here. Stay out of this kid, it's grown up business!
[14:16:54] [Client thread/INFO]: [CHAT] [Quest Book Updated]
[14:17:04] [Client thread/INFO]: [CHAT] [1/1] Vade: Hmm "Throw tribute an item to the wood that stands out, the right angle will open the way" What does this translation mean? I know it must be inside the temple, but where? Huh? Be gone, you!
[14:17:05] [Client thread/INFO]: [CHAT] [1/1] Vade: Hmm "Throw tribute an item to the wood that stands out, the right angle will open the way" What does this translation mean? I know it must be inside the temple, but where? Huh? Be gone, you!
[14:18:32] [Client thread/INFO]: [CHAT] [Info] Join a party to receive XP bonus and share the XP with your friends! For more, visit wynncraft.com
[14:22:42] [Client thread/INFO]: [CHAT] [Quest Book Updated]
[14:26:13] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:26:21] [Client thread/ERROR]: Item entity 298358 has no item?!
[14:26:21] [Client thread/ERROR]: Item entity 298358 has no item?!
[14:26:28] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:26:29] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:26:30] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:26:30] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:26:32] [Client thread/INFO]: [CHAT] You don't have enough mana to do that spell!
[14:27:17] [Client thread/INFO]: [CHAT] [Quest Book Updated]
[14:27:43] [Client thread/INFO]: [CHAT] [1/4] Vade: Hey kid, did you just come from the tomb?
[14:27:46] [Client thread/INFO]: [CHAT] [2/4] Vade: I knew I shouldn't have been so lazy and got someone else to do the leg work!
[14:27:46] [Client thread/INFO]: [CHAT] [3/4] Vade: Gosh, I can't tell my boss about this, he'll have my head! Literally! Wynn Excavation is not a group you want to betray, they are more powerful than you will ever know.
[14:27:50] [Client thread/INFO]: [CHAT] [4/4] Vade: YOU'D BETTER NOT HAVE TAKEN ANYTHING! THAT IS OFFICIAL WYNNEXCAVATION PROPERTY!
[14:27:50] [Client thread/INFO]: [CHAT] [Quest Complete: WynnExcavation Site A]
[14:27:50] [Client thread/INFO]: [CHAT] [+8000 Experience Points]
[14:27:50] [Client thread/INFO]: [CHAT] [+2 Yellow Crystals]
[14:27:55] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:55] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:57] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:57] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:57] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:58] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:58] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:27:58] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:28:08] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:28:09] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:28:09] [Client thread/INFO]: [CHAT] [1/1] Vade: Well, I figured it out soon after you got back. We possess the crystal, don't go looking for Wynn Excavation again, all is not what it seems. Take that as a friendly warning.
[14:28:31] [Client thread/INFO]: [CHAT] MisfittedCow has thrown an XP Bomb! The entire server gets double xp for 20 minutes!
[14:29:47] [Client thread/INFO]: [CHAT] [You are now entering Almuj]
[14:30:34] [Client thread/INFO]: [CHAT] _Xaxus_ left the game.
[14:30:36] [Client thread/INFO]: [CHAT] Item Identifier: Okay, I'll identify them now!
[14:30:40] [Client thread/INFO]: [CHAT] Item Identifier: It is done. Your item has been identified. The magic it contain will now blossom.
[14:30:46] [Client thread/INFO]: [CHAT] DerMixer1305 left the game.
[14:30:46] [Client thread/INFO]: [CHAT] Ov3 left the game.
[14:30:46] [Client thread/INFO]: [CHAT] Andromeda00 left the game.
[14:30:46] [Client thread/INFO]: [CHAT] GameScout180 left the game.
[14:30:46] [Client thread/INFO]: [CHAT] lolfire567 left the game.
[14:30:46] [Client thread/INFO]: [CHAT] Tomilixak left the game.
[14:30:46] [Client thread/INFO]: [CHAT] JoshNii_Chan left the game.
[14:30:46] [Client thread/INFO]: [CHAT] RaginHornet2K left the game.
[14:30:46] [Client thread/INFO]: [CHAT] MorcovTheZoroark left the game.
[14:30:46] [Client thread/INFO]: [CHAT] MisfittedCow left the game.
[14:30:46] [Client thread/INFO]: [CHAT] lily45124 left the game.
[14:30:46] [Client thread/INFO]: [CHAT] mastershednija left the game.
[14:30:46] [Client thread/INFO]: [CHAT] LittleBuckel left the game.
[14:30:46] [Client thread/INFO]: [CHAT] Roxforbraynz left the game.
[14:30:46] [Client thread/INFO]: [CHAT] Xyclus left the game.
[14:30:46] [Client thread/INFO]: [CHAT] NatsuSchultz left the game.
[14:30:46] [Client thread/INFO]: [CHAT] StickSwords left the game.
[14:30:46] [Client thread/INFO]: [CHAT] Server closed
[14:30:47] [Client thread/INFO]: [CHAT] Already connecting to this server!
[14:30:53] [Client thread/INFO]: Reloading ResourceManager: Default
[14:30:54] [Client thread/INFO]: SoundSystem shutting down...
[14:30:54] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[14:30:54] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:30:54] [Thread-24/INFO]: Initializing LWJGL OpenAL
[14:30:54] [Thread-24/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:30:54] [Thread-24/INFO]: OpenAL initialized.
[14:30:54] [Sound Library Loader/INFO]: Sound engine started
[14:30:55] [Client thread/INFO]: Created: 512x512 textures-atlas
[14:30:55] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at g.a(SourceFile:61) [1.8.7.jar:?]
	at ave.av(SourceFile:880) [1.8.7.jar:?]
	at ave.a(SourceFile:325) [1.8.7.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.7.jar:?]
Caused by: java.lang.NullPointerException
	at bcy.a(SourceFile:301) ~[1.8.7.jar:?]
	at fp.a(SourceFile:75) ~[1.8.7.jar:?]
	at fp.a(SourceFile:16) ~[1.8.7.jar:?]
	at fh$1.run(SourceFile:13) ~[1.8.7.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at g.a(SourceFile:60) ~[1.8.7.jar:?]
	... 3 more
[14:30:55] [Client thread/INFO]: [CHAT] Loading the WynnPack...
[14:30:55] [Client thread/INFO]: [CHAT] Select a class! Each class is saved individually across all servers, you can come back at any time with /class and select another class!
[14:30:55] [Client thread/INFO]: Reloading ResourceManager: Default, legacy
[14:30:55] [Client thread/INFO]: SoundSystem shutting down...
[14:30:56] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[14:30:56] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:30:56] [Thread-26/INFO]: Initializing LWJGL OpenAL

**Comment by 0Patrick0** [comment]
Sorry to say this, but they don't give back items.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!
