### ISSUE TITLE
Texture pack issues

### ISSUE THREAD

**Issue by Sythe-Wolfius** [Wynncraft/Issues#3297]
I have thoroughly searched the forums and GitHub for fixes and have tried everything, after asking for the help of several others I have no option but to give up. The game crashes once I press Ok when I am aksed if the custom texturepack can be downloaded, This is the entire log:

**[22:19:57] [Client thread/INFO]: Setting user: {Username}
[22:19:57] [Client thread/INFO]: (Session ID is token:{Token})
[22:19:58] [Client thread/INFO]: LWJGL Version: 2.9.4
[22:19:59] [Client thread/INFO]: Reloading ResourceManager: Default
[22:19:59] [Client thread/ERROR]: Couldn't initialize twitch stream
[22:19:59] [Sound Library Loader/INFO]: Starting up SoundSystem...
[22:19:59] [Thread-6/INFO]: Initializing LWJGL OpenAL
[22:19:59] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see {Link})
[22:19:59] [Thread-6/INFO]: OpenAL initialized.
[22:19:59] [Sound Library Loader/INFO]: Sound engine started
[22:20:00] [Client thread/INFO]: Created: 512x512 textures-atlas
[22:20:04] [Client thread/INFO]: {Server IP}
[22:20:13] [Client thread/INFO]: [CHAT] Your class has automatically been selected. Use /class to change your class, or /toggle autojoin to turn this feature off.
[22:20:20] [Client thread/FATAL]: Reported exception thrown!
e: Updating screen events
   at ave.s(SourceFile:1508) ~[minecraft.jar:?]
   at ave.av(SourceFile:889) ~[minecraft.jar:?]
   at ave.a(SourceFile:325) [minecraft.jar:?]
   at net.minecraft.client.main.Main.main(SourceFile:124) [minecraft.jar:?]
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
   at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545) ~[commons-io-2.4.jar:2.4]
   at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521) ~[commons-io-2.4.jar:2.4]
   at bnm.i(SourceFile:222) ~[minecraft.jar:?]
   at bnm.a(SourceFile:188) ~[minecraft.jar:?]
   at bcy$3$1.a(SourceFile:1233) ~[minecraft.jar:?]
   at awy.a(SourceFile:50) ~[minecraft.jar:?]
   at axu.a(SourceFile:350) ~[minecraft.jar:?]
   at axu.k(SourceFile:413) ~[minecraft.jar:?]
   at axu.p(SourceFile:390) ~[minecraft.jar:?]
   at ave.s(SourceFile:1498) ~[minecraft.jar:?]
   ... 3 more**

When changing the Server Resource Pack to Enabled it shows:
**Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory**
This happend every time and none of the fixes found on the forums and on GitHub changed the result.

I sincerely apologise for any time I take away from solving bigger issues,

greetings,

**Comment by Chillydog117** [comment]
I think they just need to include a physical download for the resource pack. I think that would solve these resource/texture pack issues...

**Comment by Trixter313** [comment]
If this helps at all, here's a download link for the resourcepack: https://drive.google.com/file/d/0B1ONgNZTFXnwbU9senNwaXJaR3M/view

Disabling the server resource pack and enabling this one in the resourcepacks menu should fix it and if it doesn't then it's most likely that the computer is having issues running the resource pack all together.

**Comment by Chillydog117** [comment]
Thanks!

Date: Mon, 28 Dec 2015 19:06:52 -0800

**Comment by Trixter313** [comment]
No problem, tell me if it helps at all =)

**Comment by Sythe-Wolfius** [comment]
This fixed the problem, the only issue this fix brings is that the message that tells you to download the pack keeps popping up, but besides that the texturepack makes the game fully playable. Thank you very much for your help.

**Comment by Chillydog117** [comment]
Works now. Thanks!

**Comment by Trixter313** [comment]
I'd still suggest checking periodically to see if the regular, intended way works because if you use my workaround they can't auto-update the resourcepack for you so you won't get any changes or additions.

**Comment by Chillydog117** [comment]
Okay, thanks.
