### ISSUE TITLE
I have a crash 

### ISSUE THREAD

**Issue by Phanthyo** [Wynncraft/Issues#8010]
Hello,
When I join a server and I put the resource pack, here are my logs:

[15:02:45] [Client thread/INFO]: Setting user: Phanthyo
[15:02:45] [Client thread/INFO]: (Session ID is token:6617f7617c584453bc40c4eafc68ba0f:6d0f90bc5bc943a1b12a4ff973546127)
[15:02:50] [Client thread/INFO]: LWJGL Version: 2.9.4
[15:02:51] [Client thread/INFO]: Reloading ResourceManager: Default, faithful64pack-v1.4.0.zip
[15:02:52] [Client thread/ERROR]: Couldn't initialize twitch stream
[15:02:52] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:02:53] [Thread-6/INFO]: Initializing LWJGL OpenAL
[15:02:53] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:02:53] [Thread-6/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[15:02:53] [Thread-6/ERROR]: Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
[15:02:53] [Thread-6/WARN]: ERROR MESSAGE:
[15:02:53] [Thread-6/INFO]: Could not locate OpenAL library.
[15:02:53] [Thread-6/WARN]: STACK TRACE:
[15:02:53] [Thread-6/INFO]: org.lwjgl.openal.AL.create(AL.java:156)
[15:02:53] [Thread-6/INFO]: org.lwjgl.openal.AL.create(AL.java:102)
[15:02:53] [Thread-6/INFO]: org.lwjgl.openal.AL.create(AL.java:206)
[15:02:53] [Thread-6/INFO]: paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
[15:02:53] [Thread-6/INFO]: paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
[15:02:53] [Thread-6/INFO]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
[15:02:53] [Thread-6/INFO]: paulscode.sound.CommandThread.run(CommandThread.java:121)
[15:02:53] [Sound Library Loader/WARN]: ERROR MESSAGE:
[15:02:53] [Sound Library Loader/INFO]: Could not locate OpenAL library.
[15:02:53] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:02:53] [Thread-8/INFO]: Switching to No Sound
[15:02:53] [Thread-8/INFO]: (Silent Mode)
[15:02:54] [Sound Library Loader/INFO]: Sound engine started
[15:03:12] [Client thread/INFO]: Created: 2048x1024 textures-atlas
[15:03:26] [Client thread/INFO]: Connecting to play.wynncraft.com, 25565
[15:03:31] [Client thread/WARN]: Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
[15:03:49] [Client thread/INFO]: Connecting to play.wynncraft.com, 25565
[15:04:03] [Client thread/FATAL]: Reported exception thrown!
e: Updating screen events
	at ave.s(SourceFile:1508) ~[1.8.8.jar:?]
	at ave.av(SourceFile:889) ~[1.8.8.jar:?]
	at ave.a(SourceFile:325) [1.8.8.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.8.jar:?]
Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521) ~[commons-io-2.4.jar:2.4]
	at bnm.i(SourceFile:222) ~[1.8.8.jar:?]
	at bnm.a(SourceFile:188) ~[1.8.8.jar:?]
	at bcy$3$1.a(SourceFile:1233) ~[1.8.8.jar:?]
	at awy.a(SourceFile:50) ~[1.8.8.jar:?]
	at axu.a(SourceFile:350) ~[1.8.8.jar:?]
	at axu.k(SourceFile:413) ~[1.8.8.jar:?]
	at axu.p(SourceFile:390) ~[1.8.8.jar:?]
	at ave.s(SourceFile:1498) ~[1.8.8.jar:?]
	... 3 more

**Comment by PepinhoJp** [comment]
Are you using any mods?

**Comment by Phanthyo** [comment]
No 0

**Comment by LordHelmchen98** [comment]
Have you tried other MC versions?

**Comment by ChigoMinecraft** [comment]
This isn't on topic but you see the 
[15:02:45] [Client thread/INFO]: (Session ID is token:6617f7617c584453bc40c4eafc68ba0f:6d0f90bc5bc943a1b12a4ff973546127)
part I recommend you remove that because people can hack into your account with that info.
@Phanthyo

**Comment by LordHelmchen98** [comment]
Are you still facing this issue?
